### ISSUE TITLE
Visualize Problem

### ISSUE THREAD

**Issue by zrrrleo** [prisms-center/phaseField#162]
I've already runned MgNd_precipitate_single_Bppp and gained the solution_*.vtu database.

But when I visualize the results of the simulation by the VisIt under the guidance of User manual, it seems that the results without  significant change dragging the time bar.

**Comment by david-montiel-t** [comment]
Hello zrrrleo,

Thank you for your input. 

One important thing to note is that the simulation is set in a 3D, so If you plot any of the fields in a pseudocolor plot, you will only see the outer surface of the system. Since the precipitate is seeded in one of the corners, only plots with view of that corner (or the faces that meet on the corner) will feature any evolution. 

A more informative plot for this system would probably a contour plot. Do you see any evolution when you create a contour plot of n1, for example?

Another thing to consider is that the system is not meant to show significant evolution because the initial condition was chosen to be close to the equilibrium shape. This was done because it is a relatively expensive computation and all PRISMS-PF applications with default settings are designed to run in a few minutes.

**Comment by zrrrleo** [comment]
Hello David,

Thanks for your response.

I've created a contour plot and seen the evolution.

Best wishes.
